### ISSUE TITLE
[Epic]: Network State Compression

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#4295]
https://gafferongames.com/post/snapshot_compression/
- [x] #6347
- [x] #6348
- [ ] #6349

**Comment by hamzzam** [comment]
Handle quantization errors.

_The best solution to this problem that I found was to quantize the state on both sides. This means that before each physics simulation step, I capture and quantize the physics state exactly the same way as when it’s sent over the network, then I apply this quantized state back to the local simulation.

Now the extrapolation from the quantized state on the non-authority side exactly matches the authority simulation, minimizing jitter in large stacks. At least, in theory._

[](https://gafferongames.com/post/networked_physics_in_virtual_reality/)
