### ISSUE TITLE
Validate API content and Create Bridge to Types, use jsonschema

### ISSUE THREAD

**Issue by mrhegemon** [EtherealEngine/etherealengine#5519]
Feathers <> Jsonschema <> TS

https://json-schema.org/

https://github.com/KhronosGroup/glTF/blob/main/specification/1.0/schema/glTF.schema.json

**Comment by mrhegemon** [comment]
@codenamedmitri

**Comment by speigg** [comment]
https://ajv.js.org/guide/typescript.html
