### ISSUE TITLE
Replace cube equippable with sword or something

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#5651]

**Comment by SYBIOTE** [comment]
since its the sky - station, i suggest a light saber

**Comment by HexaField** [comment]
> since its the sky - station, i suggest a light saber

that would be cool!

**Comment by SYBIOTE** [comment]
gonna look for a CC0 model first, if i find something good, ill use it else gotta make one myself

**Comment by SYBIOTE** [comment]
the sjy statiion is a techy scene, i though about a sword , but that doesnt fit well anymore as its in the sky now, not in space
