### ISSUE TITLE
[Epic] Fix & Improve Screen Share

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#6219]
- [x] fix screen share for media streaming
- [x] #6276
- [x] https://github.com/XRFoundation/XREngine/issues/6326
- [x] #6277
- [x] #6504
- [x] #6671
- [ ] #6278
- [x] #7502

**Comment by dmitrizagidulin** [comment]
Discussed briefly in the Jun 10 team sync. Our immediate needs can be addressed by #6377, leaving the screenshare stories for later.
