### ISSUE TITLE
[Story] Add static resource tables for content

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#6707]
https://docs.google.com/drawings/d/1IAIeHEaKlLC9RGu9YNA4KZBThbC_Czv6cjnzfLHDf-A

**Comment by barankyle** [comment]
https://docs.google.com/drawings/d/1IAIeHEaKlLC9RGu9YNA4KZBThbC_Czv6cjnzfLHDf-A

Items under 'Content' are current priority.

**Comment by barankyle** [comment]
Add thumbnails to image table. Images can have a thumbnail.

**Comment by barankyle** [comment]
No TypeComponent on entities, need to iterate through every entity individually and check if it needs to be converted to static resource.

When a static resource is added to a scene, it should immediately have an entry/static resource created/linked to, and the component just points to that content entry, no urls in the ECS.

**Comment by barankyle** [comment]
LOD metadata columns:

number of polys
number of verts
total texture file size
bitrate
file size
duration
pixel width
pixel depth
