### ISSUE TITLE
[Bug]: Media Server rebooting

### ISSUE THREAD

**Issue by speigg** [EtherealEngine/etherealengine#6805]
On local development, when joining a location on a separate device on the network, the media server starts rebooting continually.

**Comment by HexaField** [comment]
check that you are not in a party on any of these devices. parties and location media instances are different instances, since local dev can only run one media instance server, it will continually try to provision and load both

**Comment by speigg** [comment]
> check that you are not in a party on any of these devices. parties and location media instances are different instances, since local dev can only run one media instance server, it will continually try to provision and load both

I am not in any parties on any of these devices

**Comment by barankyle** [comment]
I tried to reproduce this with my phone and didn't see the problem reported here. If you can reproduce it, can you post the full URLs of the connections to the media server from both devices? I'm interested to see what the channelId on both connections is - if they're different, that will cause the media server to go into a loop where nothing works.

**Comment by Suley** [comment]
my k8s deployment keep rebooting too. the media server seems to be unstable.
