### ISSUE TITLE
Select avatar when entering the space

### ISSUE THREAD

**Issue by montage125** [EtherealEngine/etherealengine#7020]
When entering the space, you can select avatar and integrate Ready Player Me to let users select avatars

**Comment by HexaField** [comment]
Can you elaborate what exactly you'd like that is not currently implemented? The engine supports Ready Player Me integration and avatar upload already.

**Comment by montage125** [comment]
When users enter the space for the first time, let them choose avatars and build avatars themselves.
![image](https://user-images.githubusercontent.com/36287216/192517915-24ce4767-a3b9-4431-a9eb-c9dfc107f060.png)

**Comment by montage125** [comment]
I think it will be very cool. People like it better and increase the freedom of avatar

**Comment by HexaField** [comment]
Yes, a character creator is being planned for. There is a UI for changing avatars, and you can upload your own already.
