### ISSUE TITLE
The editor can be directly published

### ISSUE THREAD

**Issue by montage125** [EtherealEngine/etherealengine#7023]
After using the editor, you can directly publish the space
The editor needs a Publish button
As simple and convenient as hubs

**Comment by montage125** [comment]
We think it is convenient for users to click to publish directly after editing in the editor。
![image](https://user-images.githubusercontent.com/36287216/192674466-a1e0f5a6-7051-43a8-8168-a5d57d5ce2ad.png)

**Comment by HexaField** [comment]
Ethereal engine has a more complex location system than hubs, so this is not really viable.

**Comment by montage125** [comment]
This is convenient for users and creators
