### ISSUE TITLE
Exit key

### ISSUE THREAD

**Issue by montage125** [EtherealEngine/etherealengine#7024]
In the space, there is an exit button to exit the space

**Comment by HexaField** [comment]
This seems out of scope of the base engine, consider creating a project to implement this. Where do you expect this to route the user to?

**Comment by montage125** [comment]
I think in space, exit is a standard function and a part of the whole

**Comment by HexaField** [comment]
What do you mean by 'space'? Do you mean an immersive webxr session?

**Comment by montage125** [comment]
> What do you mean by 'space'? Do you mean an immersive webxr session?

yes,This is very convenient

**Comment by HexaField** [comment]
This exists, it's just disabled due out XRUI system having performance issues. We have big optimizations coming soon.
