### ISSUE TITLE
[Bug] Avatar cannot jump on mobile

### ISSUE THREAD

**Issue by montage125** [EtherealEngine/etherealengine#7026]
On the mobile phone, how does the avatar jump?

**Comment by HexaField** [comment]
There is no input assignment just yet, we used to have double tap.

**Comment by SYBIOTE** [comment]
so implement double tap jump?

**Comment by HexaField** [comment]
> so implement double tap jump? or make a button?

Double tap would be great

**Comment by SYBIOTE** [comment]
its done

**Comment by SYBIOTE** [comment]
refactoring to double tap instead

**Comment by SYBIOTE** [comment]
refactored to double tap on avatar

**Comment by SYBIOTE** [comment]
implemented the changes
