### ISSUE TITLE
[Story] Optionally use containerd vs traditional docker for k8s configuration

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#7082]
containerd by default

move to containerd in AWS

For minikube, building docker images is quite time intensive. If there is a way we can minikube to run the processes directly we can use minikube in the same way we use local dev.

https://minikube.sigs.k8s.io/docs/drivers/
Try KVM, SSH and None

- [ ] Ensure servers do not collide
- [ ] Evaluate Skaffold
- [ ] Evaluate Okteto https://www.okteto.com/

**Comment by hanzlamateen** [comment]
It seems like there are 2 part of this task:

1. Running local development on k8s (or minikube) with less install time.
2. Reconfigure the  k8 system for a more efficient driver

For the part 1, it seems like https://skaffold.dev/ & https://github.com/azure/draft could be the possible tools to help doing local dev on k8s.

I am investigating skaffold further for now.

**Comment by hanzlamateen** [comment]
https://github.com/GoogleContainerTools/skaffold/issues/8020
