### ISSUE TITLE
[Story] Collapse various settings tables into single generic table

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#7100]
We should be able to collapse all the various settings tables into one env table.

We will need to specify which pods receive each variable to preserve secrets.

We should also have a `envConfig.ts` or something in `@xrengine/common` that combines both the `config` object of `appconfig.ts` in server-core the need for a new client config, that can be access by the engine isomorphically.

This new config should be a hyperflux state, that combines all configs into one central location.

**Comment by hanzlamateen** [comment]
If this new config should be hyperflux based and combines appconfig.ts then it would be used in server packages as well? Because I dont think we are using any hyperflux based state items in server.

I guess there can be a separate config which will be used in server packages, while there can be a hyperflux state based config to be used in client packages.

Though 1 thing is that how we should have serverSettings being used in appconfig/server configs.

**Comment by HexaField** [comment]
> If this new config should be hyperflux based and combines appconfig.ts then it would be used in server packages as well? Because I dont think we are using any hyperflux based state items in server.
> 
> I guess there can be a separate config which will be used in server packages, while there can be a hyperflux state based config to be used in client packages.
> 
> Though 1 thing is that how we should have serverSettings being used in appconfig/server configs.

Thinking about this some more, there are some drawbacks with this approach. Let's keep it as plain javascript objects for now.

**Comment by hanzlamateen** [comment]
Settings Table:
key, value, scope

Settings Scope:
id, scope

This should be the database structure for generic table(s)?

Also, I had a discussion with gheric and he mentioned that we can use hyperflux state in server. So I got some idea now.

**Comment by hanzlamateen** [comment]
> We should also have a `envConfig.ts` or something in `@xrengine/common` that combines both the config object of `appconfig.ts` in server-core the need for a new client config, that can be access by the engine isomorphically.

Also, this new state thing should only deal with database entries or also env? Because the values in appconfig.ts are coming from environment variables.

**Comment by hanzlamateen** [comment]
Taking about the structure of state, should it includes all the structure like we have for appconfig.ts? If we are taking about a common state then it means either we have a generic key value map or else if we go for a strictly typed object then it will have keys like `config.kubernetes.enabled` on client side as well though its value will be null sice that value will only be populated for server pods.
