### ISSUE TITLE
Transform Component Tech Debt

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#7509]
- [x] Migrate TransformComponent & LocalTransformComponent to new component definition
- [x] Removing a TransformComponent should remove it from dirtyEntities list. We should add this to the onRemove call for the TransformComponent once it is migrated to the new component definition

**Comment by AidanCaruso** [comment]
What is the priority on migrating the transform component to the new definition? I can work on drafting that if necessary as well.

**Comment by HexaField** [comment]
> What is the priority on migrating the transform component to the new definition? I can work on drafting that if necessary as well.

That would be great!
