### ISSUE TITLE
[Bug]: Will poor network connection rate affect the frame rate?

### ISSUE THREAD

**Issue by deerleo** [EtherealEngine/etherealengine#7599]
As I dig into the code, I found out that the quality level is depending on frame rate. It will adjust base on frame rate. When I am using a poor network connect to xr server, the image quality seem to be very low. 
So the frame rate is related to network connection speed and gpu render ability, both factor will affect the frame rate?

**Comment by HexaField** [comment]
This quality metric you mention is for downgrading rendering resolution. Networking is not affected by this at all.
