### ISSUE TITLE
The help icon tooltip of `AvatarPreview` control is not working when tested in `AvatarSelectMenu.tsx` file. As shown below

### ISSUE THREAD

**Issue by jerknose** [EtherealEngine/etherealengine#7623]
The help icon tooltip of `AvatarPreview` control is not working when tested in `AvatarSelectMenu.tsx` file. As shown below

![image](https://user-images.githubusercontent.com/10975502/220597470-24bc99d0-cceb-4db5-9bb7-3aa2dab7c2d7.png)

_Originally posted by @hanzlamateen in https://github.com/XRFoundation/XREngine/issues/7583#issuecomment-1439802036_

**Comment by dikshashukla455** [comment]
greetings, Can I work on this issue?
