### ISSUE TITLE
Publish main @etherealengine/etherealengine package to NPM

### ISSUE THREAD

**Issue by jerknose** [EtherealEngine/etherealengine#7694]
Once published we can execute npx commands defined in package.json bin.

i.e npx @etherealengine/etherealengine will install everything needed for development

**Comment by HexaField** [comment]
Can you expand on what you mean by "deployment"?

**Comment by jerknose** [comment]
I wrote "development" because that the only example I've written so far. The default command is on dev in package.json as bin.etherealengine which executes the commands in /npx/cli.js

All cli.js does is run the commands from https://etherealengine.github.io/etherealengine-docs/docs/installation/

But we can define whatever we want in package.json bin:

npx @EtherealEngine/etherealengine (default)
npx @EtherealEngine/etherealengine install
npx @EtherealEngine/etherealengine build
npx @EtherealEngine/etherealengine dev

Not sure if we can point the package.json reference to shell scripts, etc.

https://docs.npmjs.com/cli/v7/commands/npx

Anyway, we can't do any of that unless we publish this package on npm as well.

**Comment by HexaField** [comment]
> I wrote "development" because that the only example I've written so far. The default command is on dev in package.json as bin.etherealengine which executes the commands in /npx/cli.js
My bad, I misread!


> All cli.js does is run the commands from https://etherealengine.github.io/etherealengine-docs/docs/installation/
> 
> But we can define whatever we want in package.json bin:
> 
> npx @EtherealEngine/etherealengine (default) npx @EtherealEngine/etherealengine install npx @EtherealEngine/etherealengine build npx @EtherealEngine/etherealengine dev
> 
> Not sure if we can point the package.json reference to shell scripts, etc.
> 
> https://docs.npmjs.com/cli/v7/commands/npx
> 
> Anyway, we can't do any of that unless we publish this package on npm as well.

What's the advantage of doing this over the existing commands?

**Comment by jerknose** [comment]
> Our plan is that the Contorl Center will be a GUI, quite like the Unreal or Unity launcher, and handle these tasks for both local dev and k8s deployment environments. We are planning on migrating our current local dev environment into a k8s dev environment.

What does that have to do with this? Did someone decide we won't support other (public, standard) ways of building? Or are you saying that all my "problems" will be solved when this comes out Soon™

**Comment by HexaField** [comment]
> What does that have to do with this? Did someone decide we won't support other (public, standard) ways of building? Or are you saying that all my "problems" will be solved when this comes out Soon™

Just informing you of what has already been in the works. The are reasons we want to migrate away from the current local dev experience (limited instance servers, discrepancies from deployed environments, workflow issues, limited & difficult windows/WSL support). So, essentially, yes, we don't want to support the current local dev environment.

**Comment by jerknose** [comment]
> Just informing you of what has already been in the works. The are reasons we want to migrate away from the current local dev experience (limited instance servers, discrepancies from deployed environments, workflow issues, limited & difficult windows/WSL support). So, essentially, yes, we don't want to support the current local dev environment.

That's why I said "Publish main @etherealengine/etherealengine package to NPM" and not "Support the current local dev environment through some new scripting thingy"

And as much as I want us to have our own Epic Games Launcher, we do still care about improving the user experience for those who manually install, right? With this, our install instructions can be one command. 

This is work that is already done. The code was merged in 3 weeks ago. All I'm asking for is to finished the job by publishing this repo. Just like all the others.
