### ISSUE TITLE
Need to add oAuth redirect urls for local.etherealengine.org

### ISSUE THREAD

**Issue by hanzlamateen** [EtherealEngine/etherealengine#7696]
So for our local k8s environment we migrated from local.etherealengine.com to local.etherealengine.org. We need the new .org domain to be added in redirect urls of auth providers like google, github, etc so the login works.

**Comment by barankyle** [comment]
I updated the callback URLs on all of the OAuth apps that we use for local. .env.local.default's values should be the only thing left.
