### ISSUE TITLE
[Bug]: Overflow in x direction 

### ISSUE THREAD

**Issue by himanshu1221** [EtherealEngine/etherealengine#7768]
There is overflow in x direction if maintainers finds this issue valid then I would love to work on this issue

![Screenshot from 2023-03-17 22-53-45](https://user-images.githubusercontent.com/32031706/225975604-4373846c-6746-4026-b06f-e19d23141c82.png)

**Comment by HexaField** [comment]
This repository is for the engine itself, the website is being rewritten currently.

If you'd like to contribute to the engine, please get in contact with us on our discord.

**Comment by himanshu1221** [comment]
> This repository is for the engine itself, the website is being rewritten currently.
> 
> If you'd like to contribute to the engine, please get in contact with us on our discord.

I would be more happy to contribute in rewriting your website as of now 
How can i help you with that ?
