### ISSUE TITLE
[Bug]: Preview Camera offset in the y-axis 

### ISSUE THREAD

**Issue by 2dels** [EtherealEngine/etherealengine#7858]
The preview camera creates a thumbnail in the correct location but upon re-opening the scene, the viewport camera is offset in the y-axis and does not match the thumbnail location.

**Comment by HexaField** [comment]
This is due to most of the scenes not having a scene-preview-camera configued correctly, I suspect the component identitifer got changed at some point and subsequently removed. The functionality is working as expected.
