### ISSUE TITLE
[Bug]: "Save As" broken on local development

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#7862]
Unable to resave scene with new name

On local dev, pressing "Save As" causes the scene to stop rendering and no save modal appears. Works correctly on dev deployment.

**Comment by dinomut1** [comment]
Update: On local, save modal appears, and when you enter a scene name and press "Save", the scene does get saved, but the modal never closes, and you have to refresh the scene tab to see that the scene has been saved

**Comment by speigg** [comment]
Can't reproduce
