### ISSUE TITLE
[Bug]: Issues loading custom made avatar

### ISSUE THREAD

**Issue by mimipixiiie** [EtherealEngine/etherealengine#7958]
Is there any way to load and use a custom made avatar instead of readyplayer.me avatars? When I try to load an avatar from another website, it sometimes doesn't load, and sometimes the loaded avatar's body parts/ bone structure changes and avatar body shape is not correct. Is there a way to fix this?

**Comment by HexaField** [comment]
We have a lot of avatars that are supported (Reallusion, VRM, Mixamo) but no way currently to manually retarget. See this issue https://github.com/EtherealEngine/etherealengine/issues/3551
