### ISSUE TITLE
[Bug]: Transform not applying to objects in scene

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#7970]
If a model component's src is changed, the new scene will not update transforms according to moving the gizmo or updating the transform component properties: 
![Screenshot from 2023-05-04 16-08-45](https://user-images.githubusercontent.com/94419856/236349022-f354efd0-7c6f-4783-9d33-956818832c56.png)

**Comment by HexaField** [comment]
Gizmo also seems to not update properly
