### ISSUE TITLE
Implement Docker multi-stage cache in ECR once Buildkit 0.12 is released

### ISSUE THREAD

**Issue by barankyle** [EtherealEngine/etherealengine#7984]
https://github.com/aws/containers-roadmap/issues/876

In order to cache all stages of a multi-stage build, once must use newer features of BuildKit, specifically cache manifests. The builder build command would look something like:

```
docker buildx build \
  --push \
  -t $ECR_URL/$REPO_NAME-builder:latest_$STAGE \
  -t $ECR_URL/$REPO_NAME-builder:"${EEVERSION}_${TAG}" \
  --cache-to type=registry,ref=$ECR_URL/$REPO_NAME-builder:latest_"${STAGE}"_cache,mode=max \
  --cache-from $ECR_URL/$REPO_NAME-builder:latest_"${STAGE}"_cache \
  -f dockerfiles/builder/Dockerfile-builder .
```

Cache manifests are not supported in ECR right now. They should be some time after BuildKit 0.12 is released; AWS engineers were waiting for a feature that was recently merged into the BuildKit spec in order to support this.

**Comment by phonezawphyo** [comment]
Eagerly waiting for it.
