### ISSUE TITLE
Admin Server Page should show Media Server Type

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#8028]
![Screenshot from 2023-05-30 08-35-38](https://github.com/EtherealEngine/etherealengine/assets/10372036/4c9a0213-0899-4e7e-aadf-f95d61b5ce5b)

Similar to the world servers, we should show whether each media server is either assigned to a world location, or is a party.

Should look like:
`World (apartment)`
`Media (apartment - instanceId)` - where instanceId is the associated world server instanceId
`Media (Party)`

**Comment by SYBIOTE** [comment]
is it possible for a media server to belong to both a world location and a party/channel?
if yes ill make a separate commit
for now i am proceeding with the assumption that they are mutually exclusive

**Comment by HexaField** [comment]
> is it possible for a media server to belong to both a world location and a party/channel? if yes ill make a separate commit for now i am proceeding with the assumption that they are mutually exclusive

no, they are separate servers
