### ISSUE TITLE
[Bug]: Stray avatar appears in the engine after OAuth logout

### ISSUE THREAD

**Issue by saniyat013** [EtherealEngine/etherealengine#8095]
![Screenshot from 2023-06-16 11-18-31](https://github.com/EtherealEngine/etherealengine/assets/32844821/c3803dc9-f6b0-4964-905a-5c9b6863571f)

I have configured GitHub login and logged in using my GitHub account (Browser 1). Then I set a custom avatar, which is marked as number 1 in the image. In another browser (Browser 2), I joined the world as a guest, which is avatar number 2. Then I logged out as a GitHub user and joined the page as a guest by default (Browser 1). This time I had the guest avatar, which is number 3.
But when I reload the browsers, **the first customized avatar returns in both browsers, though the GitHub account is not connected at all.**
And surprisingly if I log in again with GitHub and log out, another copy arises.
**This means there appears a stray avatar, as per the number of times I log out from the logged-in state.**

**Comment by HexaField** [comment]
will be solved with https://github.com/EtherealEngine/etherealengine/issues/8124
