### ISSUE TITLE
[Bug]: Can't set "Location" while creating a portal  

### ISSUE THREAD

**Issue by Mustafiz48** [EtherealEngine/etherealengine#8096]
In studio while editing the scene, I have added a portal. Now to customize the portal, in the properties, I can't set the  Location property. The input box doesn't take any input. Whatever I type, it  doesn't show up in the box. I tried pasting a text, it doesn't work either. I tried other field (like Preview Image URL) and they works.

![portal_problem](https://github.com/EtherealEngine/etherealengine/assets/46300763/409d2130-aafb-47ba-aae7-14dc984c7b7c)

**Comment by SYBIOTE** [comment]
just fixed this, changed , the component form StringInput to ControlledStringInput,  now the changes can be seen visually
