### ISSUE TITLE
[Feature] add manual KTX2 browser caching

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#8125]
The browser does not cache KTX2 assets by default.

We can do this manually by utilizing localstorage/indexdb and interupting the AssetLoader

**Comment by SYBIOTE** [comment]
looks like i just need to use loader.load method from KTX2 loader in threejs, that will auto cache the file in the browser, illhave to test this implementation though 
first must identify all the places where we use load KTx2 textures from

**Comment by SYBIOTE** [comment]
this was confirmed as working right?
