### ISSUE TITLE
Post Processing Settings are not Reactive

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#8134]
In the studio post processing settings UI, when releasing a slider, toggling a button or losing focus on a input values, the setting should be updated

**Comment by SYBIOTE** [comment]
where do i find this editor in the studio?

**Comment by HexaField** [comment]
> where do i find this editor in the studio?

scenes that have post processing on the scene node will have it. it can be added to the scene entity too.

**Comment by SYBIOTE** [comment]
fixed

**Comment by dinomut1** [comment]
Still observing this bug on latest dev

**Comment by HexaField** [comment]
We still want to improve this so I'll keep it open
