### ISSUE TITLE
Improve drag and drop file import

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8149]
Something to do with react-dnd not detecting it when window comes into focus

**Comment by SYBIOTE** [comment]
https://github.com/EtherealEngine/etherealengine/assets/54761979/80fa8b48-ff1e-49fa-b511-abb2be6c1c94

isn't this working as intended?

**Comment by SYBIOTE** [comment]
I can drag the gab file directly onto the viewport and it shows the upload symbol, I can drop it directly into the file as well
I think this issue is already resolved
