### ISSUE TITLE
Set from viewport and portal preview should actually show preview of what the thumbnail looks like

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8156]
Should render a frame into a new canvas every time the transform changes

**Comment by SYBIOTE** [comment]
so we want the portal preview on the portal itself?

**Comment by HexaField** [comment]
> so we want the portal preview on the portal itself?
> where is the set from viewport option? is it also from the portal?

The portal uses an envmap bake to generate the preview. We want to also have a copy of this on a square image in the properties panel under the component editor view.

**Comment by SYBIOTE** [comment]
a square image on properties, roger that
