### ISSUE TITLE
Studio color picker broken

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8157]

**Comment by SYBIOTE** [comment]
we have a color picker in the admin -> settings -> clientTheme , that works well

**Comment by HexaField** [comment]
> we have a color picker in the admin -> settings -> clientTheme , that works well where do we use the color picker in the studio?

on any of the light components, ground component, sky component. search for ColorInput in the codebase

**Comment by SYBIOTE** [comment]
ColorInput roger that

**Comment by SYBIOTE** [comment]
diagnosis, its working but the picker itself is not visually reacting to changes

**Comment by SYBIOTE** [comment]
fixed it

**Comment by SYBIOTE** [comment]
although i am unsure how the defaults can be set on startup

**Comment by SYBIOTE** [comment]
refactoring to use Color as prop instead of string fixed it
