### ISSUE TITLE
Improve Editor CSS

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8159]

**Comment by SYBIOTE** [comment]
how do errors show right now

**Comment by HexaField** [comment]
> how do errors show right now
> 

Invalid source

**Comment by SYBIOTE** [comment]
renaming issue:
Error CSS needs to be improved (put errors on the left, inside of error icon w/ popup text)

**Comment by SYBIOTE** [comment]
the task has evolved to cover the whole engine

**Comment by SYBIOTE** [comment]
its done

**Comment by SYBIOTE** [comment]
the task evolved to moving all styled components to pure external and inline css, then polishing said css to make the editor look better
part one is done
ill start part two soon as well

**Comment by SYBIOTE** [comment]
we need to QA this
