### ISSUE TITLE
[Story] revisit spotlight decay and make sure calibrated

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8178]

**Comment by SYBIOTE** [comment]
under stood spotlight decay, what does calibration mean?

**Comment by SYBIOTE** [comment]
we already have decay for spotlight, its based on the threejs implementation , how do we intend to augment it?

**Comment by SYBIOTE** [comment]
Still relevant?

**Comment by HexaField** [comment]
> Still relevant?

yes, basically we just need to make sure the defaults in SpotLightComponent are the same as the defaults in threejs

**Comment by Griffisaurus** [comment]
I don't think so.  This may have been a bug messing things up but not present
anymore.
On Mon, Oct 2, 2023 at 3:21 PM Rahul Ghosh ***@***.***> wrote:


Still relevant?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>


Sent with Mixmax
