### ISSUE TITLE
[Bug]: Navigating directly to a scene in the Studio doesn't consistently load the scene

### ISSUE THREAD

**Issue by speigg** [EtherealEngine/etherealengine#8219]
Navigating directly to a scene in the studio doesn't work reliably. 

E.g. https://dev.etherealengine.com/studio/eepro-showroom-rooftop/cars

**Comment by aditya-mitra** [comment]
If the user does not have the **editor:write** permission, he would redirected to the auth page. This is the current behaviour and I think this the expected behaviour as well.

Reference: https://github.com/EtherealEngine/etherealengine/blob/dev/packages/client/src/pages/editor/editor.tsx#L51-L61
