### ISSUE TITLE
[Bug]: Studio - saving scene w/ thumbnail and envmap breaks the editor camera

### ISSUE THREAD

**Issue by speigg** [EtherealEngine/etherealengine#8221]
The studio (specifically the camera controls) becomes unusable after saving w/ thumbnail and envmap generation. Page needs to be reloaded.

**Comment by SYBIOTE** [comment]
i am seeing a pattern, here all sort of webgl texture renders are failing for some reason

**Comment by SYBIOTE** [comment]
cannot recreate this bug

**Comment by SYBIOTE** [comment]
is this still broken?

**Comment by SYBIOTE** [comment]
i think this is fixed, closing this
