### ISSUE TITLE
Replace React Dock with custom dock

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#8259]
`rc-dock` sucks

We might want to fork it, or just create our own. Use raw css style tags, so we can migrate it to tailwind easily when the studio route uses tailwind.

**Comment by SYBIOTE** [comment]
what are the pain points?

**Comment by HexaField** [comment]
> what are the pain points?

It's very limiting, we would like to be able to drag to resize, pop in and out, show & hide / minimize & maximize, and have all these styles be completely customized.

**Comment by SYBIOTE** [comment]
probably can be integrated in the improve editor css task

**Comment by SYBIOTE** [comment]
collecting docks
https://github.com/Dirkster99/AvalonDock

https://www.npmjs.com/package/flexlayout-react

https://github.com/mathuo/dockview

https://github.com/hlorenzi/react-dockable

**Comment by timadevelop** [comment]
Hi all, have you been able to find something better than `dockview` so far?

We want to replace GL in one of our apps and it seems like other solutions like DockSpawn, react-dockable, etc. are either abandoned or not ready for prod yet.

Hence I'm thinking about replacing our current dock lib with `dockview`. It'd be great to know if more people are willing to commit to the lib as it would give hope project doesn't end up abandoned. There's also https://github.com/jupyterlab/lumino that "absorbed" Phosphor JS before and seems to be supported by JupiterLab, it doesn't cover all of our requirements though.

@HexaField @aditya-mitra Are you still open to utilizing third-party lib or you rather want to go the "vscode" route and write custom docking logic?

**Comment by HexaField** [comment]
hey @timadevelop we did find a replacement, thanks anyway!
