### ISSUE TITLE
admin invites page doesnt load

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#8273]
@mui/x-date-time doesnt build

local build can be tested with `npm run local`

**Comment by SYBIOTE** [comment]
loaded in localhost

![Image](https://github.com/EtherealEngine/etherealengine/assets/54761979/d00228cd-b0ce-4be6-a790-d5ba591d66d2)

**Comment by SYBIOTE** [comment]
doesnt load in dev-deployment

**Comment by SYBIOTE** [comment]
update @mui/x-date-time to latest version fixes this

**Comment by HexaField** [comment]
> update @mui/x-date-time to latest version fixes this

the API has changed though, so we need to make sure the funcitonality still works
