### ISSUE TITLE
Preview in Studio does not show preview of glb 3d models.

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8290]

**Comment by Griffisaurus** [comment]
clicking on a glb model in the file browser does not load a preview.  The box remains black.  Other file types work.

**Comment by HexaField** [comment]
https://github.com/EtherealEngine/etherealengine/pull/8239

**Comment by HexaField** [comment]
duplicate https://github.com/EtherealEngine/etherealengine/issues/8152
