### ISSUE TITLE
Behave Graph integration

### ISSUE THREAD

**Issue by speigg** [EtherealEngine/etherealengine#8309]
https://github.com/bhouston/behave-graph https://github.com/beeglebug/behave-flow

- [ ] ECS manipulation node
- [ ] State manipulation node
- [ ] Action dispatch node

**Comment by SYBIOTE** [comment]
so we need to add a behave graph component to get the old system working
i am creating a new node editor , and prefab for the component and addign it that way into the engine, once it works ill port it to the latest ee-behave-flow implementation
