### ISSUE TITLE
[Bug]: Add component button missing in studio properties panel

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8374]
Even with advanced mode enabled there is no longer a button to add components to entities
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/f84c4be3-a55f-4efc-8ca1-57706f116e9a)

**Comment by HexaField** [comment]
This has been replaced by the components shelf. You can drag components from the right into the properties or onto an entity to add it.

**Comment by dinomut1** [comment]
many components aren't present on the shelf. also, the volumetric component requires a media component to work, which should be automatically added to the entity instead of requiring that the user know component dependencies and manually drag them all onto the entity
