### ISSUE TITLE
[Bug]: Download Project Button Doesn't Work

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8478]
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/c415eca8-e9da-4af6-a19a-64e6a2f5a1a1)
Nothing happens when this button is pressed. No errors are thrown either.

**Comment by barankyle** [comment]
Fixed via commit 371fd2fb46856103d4be013ca992cc751e6459d0
