### ISSUE TITLE
[Bug]: "GetEntityInScene" node serializes to Entity rather than entity UUID

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8494]
Given this scene graph:
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/e1280b8f-0e96-4930-bc08-fbe171a5aeeb)

The editor entity array looks like this:

![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/ed9c818f-d932-45a8-95cb-77fda63c09c0)

I create a Behave Graph with this configuration, which is supposed to take the "New Image" node and remove its VisibleComponent after 5 seconds:
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/480b3456-2dd3-408c-a050-10a9dbd44194)

The graph is serialized with the target entity as "15":
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/8c6c9e26-c03f-43fb-8fc7-ae1e377faea1)

Now, when i enter this scene outside of the editor, the entity array looks like this:

![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/25c5bb22-7c0b-40bd-9bcf-40e25c4f2124)

Entity 15 is now the spawn point instead of the image. So the graph executes and it makes the spawn point invisible instead of the image.

This can be fixed by serializing the entity UUID instead of the entity itself when selecting from the scene.

**Comment by SYBIOTE** [comment]
I fixed this it should work now
