### ISSUE TITLE
Expose node configuration in behave flow UI

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8522]
Expose the fields of the schema to the behave flow UI so that each node can be mutated to customize functionality (e.g. sequence node adding a customized number of output sockets)

**Comment by SYBIOTE** [comment]
this is done, to some capacity, we can expose config to the UI now

**Comment by SYBIOTE** [comment]
we saw bugs on core bhg, bcz of this, fixed those bugs

**Comment by SYBIOTE** [comment]
this is done, closing this
