### ISSUE TITLE
Add GetComponent node to behave graph

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8523]
GetComponent node in behave graph that lets the user select the component tied to a behavior on the output sockets.  The selector should not be hard-coded to each component but rather identify every component available to the user through the studio and use the component's schema to establish connectors

**Comment by SYBIOTE** [comment]
this is done

**Comment by SYBIOTE** [comment]
https://github.com/EtherealEngine/etherealengine/pull/8571

right now we cover 61/91 components 
we can edit all properites which are either, entity, number, boolean , string , vec3, vec2, mat , color

**Comment by SYBIOTE** [comment]
this is merged
