### ISSUE TITLE
[Bug]: MediaComponent doesn't loop when there is only one track

### ISSUE THREAD

**Issue by CITIZENDOT** [EtherealEngine/etherealengine#8565]
https://github.com/EtherealEngine/etherealengine/blob/b261be8fc81a157b63180b779581a74a2bc99283/packages/engine/src/scene/components/MediaComponent.ts#L344-L352

`getNextTrack` is called when there is a change in `[media.resources, media.track]`.
`getNextTrack` returns the same trackId when:
- When there is only one track and `playMode` is set to loop
- there are multiple tracks and `playMode` is set to `PlayMode.singleloop`

When this happens, `media.track` is not changed and the above hook is not triggered. Hence the media stops after one playback.

**Comment by HexaField** [comment]
Might be solved, needs QA

**Comment by CITIZENDOT** [comment]
This is solved in `VolumetricComponent` by using `hasTrackStopped` state.
