### ISSUE TITLE
[Bug]: Dragging and dropping items to be child of a scene element still places it at the origin

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8568]
When placing an EntityNode as a child of another EntityNode, its transform is set so that its world position remains at the origin. This shouldn't happen, and the local transform of the new EntityNode should be 0,0,0 instead of the negation of its parent
[Example](https://github.com/EtherealEngine/etherealengine/assets/94419856/8f9b8240-7574-4568-b671-5cf436c8cba5)

**Comment by HexaField** [comment]
Might be solved, needs QA

**Comment by SYBIOTE** [comment]
any update on this?

**Comment by SYBIOTE** [comment]
i think this is solved as well, we don't see parent negation, unless it's the race condition and we have a PR up for that.

**Comment by HexaField** [comment]
@dinomut1

**Comment by SYBIOTE** [comment]
still relevant? im closing this
