### ISSUE TITLE
[Bug]: No URL Field for Positional Audio Component

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8630]
There's no way to set a URL for audio

**Comment by dinomut1** [comment]
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/d623f4ad-7167-47c8-a571-78537e65ec88)

**Comment by HexaField** [comment]
Should be in the MediaComponent

**Comment by dinomut1** [comment]
closed by 4c188d609391d6e643e3633685617ad22a5b05d6
