### ISSUE TITLE
[Bug]: Directional Light Doesn't Update Intensity

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8632]
[Screencast from 08-30-2023 10:01:50 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/d8cfc90f-495f-41a5-8963-260829cf21ff)

**Comment by SYBIOTE** [comment]
strange in local dev rn , dir light intensity does work

https://github.com/EtherealEngine/etherealengine/assets/54761979/43b3cbb0-8617-4d66-b32a-98de045feacc
