### ISSUE TITLE
Re-write Transform Gizmo

### ISSUE THREAD

**Issue by SYBIOTE** [EtherealEngine/etherealengine#8660]
- [ ] re-implement [Threejs' Transform Controls](https://github.com/mrdoob/three.js/blob/master/examples/jsm/controls/TransformControls.js) into a re-usable ECS Component, without creating sub-objects

**Comment by mrhegemon** [comment]
look at three js
make a component

**Comment by SYBIOTE** [comment]
The gizmo is a component and  uses a extended 3dobject 
So we remove that extended 3d object and refactor it to work within the component entirely?

Atm I have finished creating a combined transform manipulator

**Comment by SYBIOTE** [comment]
made significant progress, but still figuring out how the gizmo handles local transform as the transform is overridden by local transform right now
