### ISSUE TITLE
Cleanup Engine class

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#8696]
The engine instantiates all our globals, but does too much directly, and should contain/manage only the following:
- data modules (ECS store / hyperflux store)
- logic modules (system pipeline and reactors)

Things to move
- [x] move `worldNetwork`, `worldNetworkState`, `mediaNetwork`, `mediaNetworkState` to `NetworkState` defintion
- [x] remove deprecated `deltaSeconds`, `elapsedSeconds`, `fixedTick`, `fixedDeltaSeconds`
- [x] remove `priorityAvatarEntities` and get from `AvatarAnimationState`
- [x] move `pointerScreenRaycaster` and `pointerState` to `InputState`
- [x] move `activePortalEntity` to `PortalComponent` definition
- [x] move `xrFrame` to `XRState` defintion
- [x] move `gltfLoader` to a new `AssetLoaderState` in AssetLoader.ts

We also have things like `scene`, `origin`, `originEntity`, `camera`, `cameraEntity`, `objectLayerList` which are scene specific, and are fine to stay here until the various scene state & ECS hierarchy refactors have come through

**Comment by anselm** [comment]
pretty much done at this point - just have to check the pull requests
