### ISSUE TITLE
[Bug]: Hierarchy Panel is Blank When Switching Back from Material Library

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8704]
In the studio, after selecting a different tab of the panel holding the Hierarchy, when switching back to hierarchy the panel is blank
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/346ab5db-7ad8-41ef-b56e-18535d74d898)

**Comment by SYBIOTE** [comment]
cannot reproduce in local or dev

**Comment by SYBIOTE** [comment]
i think its happens when there is no entity selected / under focus 
im not sure how that triggers when switching back from the material panel though

**Comment by SYBIOTE** [comment]
cannot replicate, closing
