### ISSUE TITLE
Move File Browser Refresh Button onto Shelf Header

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8710]
[Screencast from 09-08-2023 06:25:20 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/406fa589-9e8e-4ecc-aaab-e68e3d95abb7)

Move the refresh button onto the file browser header so that it remains in view even when scrolling down

**Comment by SYBIOTE** [comment]
i fixed the shelf itself, and made only the files part scrollable
