### ISSUE TITLE
[Bug]: Sometimes Middle Mouse Click Spawns Most Recently Placed Model Component

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8711]
[Screencast from 09-09-2023 01:10:39 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/25075fb3-22db-4b1a-ab7a-71d8b270b845)

Sometimes, on both local and deployment, after placing a model into the scene, middle mouse clicking will generate an additional copy of that model in the scene graph. This continues to happen after refreshing the page and the only way to stop it on local is to restart the dev environment entirely.

**Comment by SYBIOTE** [comment]
cant seem to reproduce this issue

**Comment by HexaField** [comment]
> cant seem to reproduce this issue

you might need to copy something first?

**Comment by SYBIOTE** [comment]
the issue indicates that pressing middle mouse button copies stuff when its not supposed to, does this trigger on copy? @dinomut1

**Comment by dinomut1** [comment]
@SYBIOTE more info on this one. middle mouse click triggers a "paste" operation. If you have anything in your clipboard it will attempt to paste it into the scene

**Comment by SYBIOTE** [comment]
i think @HexaField , already made changes to stop this from happening, i still dont know why it happens tho
