### ISSUE TITLE
[Bug]: Page Index does Not Reset When Changing Folder in File Browser

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8714]
In the file browser, if you are in one folder, and you change page index, if you switch to another folder, you stay on that page index. In the below example, I am going to the second page of the "assets" folder, but then when I change folder to the project root, I am now on a nonexistent page 2 of that menu even though no second page exists, thus the file browser is blank:
[Screencast from 09-09-2023 02:11:55 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/cbf9f5bd-4b38-4ea1-91c5-2053ec71e27d)

Every time you change folders in the file browser the page index should reset to 1

**Comment by aditya-mitra** [comment]
implemented by #8800
