### ISSUE TITLE
[Bug]: Parent Transforms Getting Negated in Children

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8847]
To reproduce:
In any scene, add an image or gltf model to the scene. Offset it slightly, or leave it at origin. the transform of the child element is irrelevant to this bug:

![Screenshot from 2023-09-19 12-33-39](https://github.com/EtherealEngine/etherealengine/assets/94419856/afb5e33f-ccac-4f17-b210-752e669526d3)

Next, add another element to the scene and add the model/image as a child of that element. Adjust the transform on the parent in any way:

![Screenshot from 2023-09-19 12-33-27](https://github.com/EtherealEngine/etherealengine/assets/94419856/5a9a1c8d-d722-4d25-a182-0bdbc598f52b)

Next save the scene and refresh. When the scene loads again, the child element will have its transform modified to negate the parent transform:

![Screenshot from 2023-09-19 12-34-37](https://github.com/EtherealEngine/etherealengine/assets/94419856/6753b61a-713e-44f3-a3eb-193165238fe4)

**Comment by SYBIOTE** [comment]
issue is resolved
