### ISSUE TITLE
Add docs to setup opensearch locally

### ISSUE THREAD

**Issue by hanzlamateen** [EtherealEngine/etherealengine#8853]
Add a new guide in our docs under `8_opensearch.md`

https://github.com/EtherealEngine/etherealengine-docs/tree/master/docs/1_host/1_installation

Check this: https://github.com/EtherealEngine/etherealengine/pull/8583#issuecomment-1696894873
You would need to copy .env.local.default & enable VITE_FORCE_CLIENT_LOG_AGGREGATE=true

**Comment by HexaField** [comment]
Rather than just copying the env file, we should specify all the variables involved

**Comment by ashish-aesthisia** [comment]
> Rather than just copying the env file, we should specify all the variables involved

Yes copying whole file is not required as user might be having their own settings

**Comment by ashish-aesthisia** [comment]
PR: https://github.com/EtherealEngine/etherealengine-docs/pull/33
