### ISSUE TITLE
[Bug]: When Adding KTX2 To Image Component, Scene Does Not Save

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8873]
To reproduce: In any scene, add an image component, and set the src to a .ktx2 image. Then try to save the scene. The "Saving Project" buffer hangs forever, and the scene fails to save. Upon switching the image src to any uncompressed image type, the scene successfully saves immediately.

**Comment by DanielBelmes** [comment]
interestingly only reproducible on production.

**Comment by DanielBelmes** [comment]
Bug occured when server would download ktx2 image and attempt to run a .parse function that was not defined.
