### ISSUE TITLE
[Bug]: Asset Loading Race Condition in Studio

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8891]
When loading scenes in the studio, the assets are not guaranteed to complete loading. 
Reproduced consistently in https://dev.etherealengine.com/studio/eepro-arcade/arcade where the dancing npc avatars sometimes load, sometimes do not, even through the scene thinks it is fully loaded every time

**Comment by CITIZENDOT** [comment]
Is this reproducable with any other projects/scenes? arcade is not reproducable since avatar assets are missing.
