### ISSUE TITLE
Websocket connection failed.

### ISSUE THREAD

**Issue by meeeo** [EtherealEngine/etherealengine#8924]
I installed etherealengine on a server with a static IP, I follow the notes in .env.local to modified the listen address.
Every things fine, but with a "connecting to media.." message and got lots of errors messages in chrome console, and some error logs in server.
Not sure what's wrong, thanks for your suggestion.
![Screen Shot 2023-09-28 at 3 57 37 PM](https://github.com/EtherealEngine/etherealengine/assets/5188710/6fd98ecf-29c7-485a-8cdb-545eff0a8295)
![Screen Shot 2023-09-28 at 4 16 54 PM](https://github.com/EtherealEngine/etherealengine/assets/5188710/ae4d4269-ecc8-41a4-ab97-6fd40e37fc59)
![Screen Shot 2023-09-28 at 4 51 58 PM](https://github.com/EtherealEngine/etherealengine/assets/5188710/5e573103-ff1c-415a-975e-a327e5e3d0b5)

**Comment by hanzlamateen** [comment]
@meeeo you need to accept certificates as mentioned on: https://etherealengine.github.io/etherealengine-docs/docs/host/installation/windows_wsl#start-engine-stack

**Comment by meeeo** [comment]
> @meeeo you need to accept certificates as mentioned on: https://etherealengine.github.io/etherealengine-docs/docs/host/installation/windows_wsl#start-engine-stack

Thank you for your reply, I didn't see anything related to accepting certs in the link you gave, I think you may mean this one? 
https://etherealengine.github.io/etherealengine-docs/docs/host/devops_deployment/minikube/#accept-invalid-certs

**Comment by hanzlamateen** [comment]
> > @meeeo you need to accept certificates as mentioned on: https://etherealengine.github.io/etherealengine-docs/docs/host/installation/windows_wsl#start-engine-stack
> 
> Thank you for your reply, I didn't see anything related to accepting certs in the link you gave, I think you may mean this one? https://etherealengine.github.io/etherealengine-docs/docs/host/devops_deployment/minikube/#accept-invalid-certs

Follow below section in the link I send you

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/c44e8a57-b1f9-4b86-aefd-e6e50af94022)

You might also have to accept minio certificate running on port :9000.

**Comment by meeeo** [comment]
> > > @meeeo you need to accept certificates as mentioned on: https://etherealengine.github.io/etherealengine-docs/docs/host/installation/windows_wsl#start-engine-stack
> > 
> > 
> > Thank you for your reply, I didn't see anything related to accepting certs in the link you gave, I think you may mean this one? https://etherealengine.github.io/etherealengine-docs/docs/host/devops_deployment/minikube/#accept-invalid-certs
> 
> Follow below section in the link I send you
> 
> ![image](https://user-images.githubusercontent.com/10975502/271242756-c44e8a57-b1f9-4b86-aefd-e6e50af94022.png)
> 
> You might also have to accept minio certificate running on port :9000.

Oh, I see now, thank you!
