### ISSUE TITLE
[Bug]: Resetting Media in Studio Automatically Plays Clip

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8932]
To reproduce: Place an audio clip into the scene. Press the pause button. Then press the reset button. The clip will automatically start playing.

Audio clips should not automatically play when you reset them. otherwise there is no way to get the audio clip to be paused and at the start of the seek time.

**Comment by CITIZENDOT** [comment]
Fixed in #8926

**Comment by CITIZENDOT** [comment]
Can we close this?
