### ISSUE TITLE
[Bug]: Cannot Drag and Drop .bin files (and likely other file types)

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8942]
![brave_7y2EdOtNtO](https://github.com/EtherealEngine/etherealengine/assets/94419856/34a9c804-9ae3-440e-8625-d095eb3149a7)

**Comment by CITIZENDOT** [comment]
The type of files that can be moved around is defined here: https://github.com/EtherealEngine/etherealengine/blob/71af8a242d99acfe39e9c5062bfe3a51c1e6427f/packages/editor/src/components/assets/FileBrowserGrid.tsx#L267 Unfortunately, there is no wild card `accept` type in react-dnd ([Related issue](https://github.com/react-dnd/react-dnd/issues/432#issue-146851937)).

Incase, moving around `bin` file is necessary, we can simply add `bin` type to `accept` prop:
```ts
accept: [...SupportedFileTypes, 'bin'],
```

**Comment by HexaField** [comment]
> The type of files that can be moved around is defined here: https://github.com/EtherealEngine/etherealengine/blob/71af8a242d99acfe39e9c5062bfe3a51c1e6427f/packages/editor/src/components/assets/FileBrowserGrid.tsx#L267 Unfortunately, there is no wild card `accept` type in react-dnd ([Related issue](https://github.com/react-dnd/react-dnd/issues/432)).
> 
> Incase, moving around `bin` file is necessary, we can add `bin` type to `accept` prop:
> ```ts
> accept: [...SupportedFileTypes, 'bin'],
> ```

There is already a PR up for this

**Comment by CITIZENDOT** [comment]
Ah! Haven't noticed it.
