### ISSUE TITLE
[Bug]: Admin avatar drawer issues

### ISSUE THREAD

**Issue by barankyle** [EtherealEngine/etherealengine#8978]
Saw a couple of issues with the admin avatar create/edit drawer:

In create mode, the preview of the selected model is not shown. Without that, there's no indication that a file has been successfully selected/uploaded.

When opening the drawer in edit mode, most of the buttons for changing files, and toggling between file and URL upload, are selectable before pressing the "Edit" button, which is confusing. I think they are all supposed to be disabled until one presses Edit, and before that, it should just show previews of the current model and thumbnail.

**Comment by HexaField** [comment]
@aditya-mitra was this solved entirely by your PR? or is there still work to do?

**Comment by aditya-mitra** [comment]
There is still the avatar preview in create mode left. There seems to be currently no way to preview the avatar without uploading it.
