### ISSUE TITLE
error messages from Using Local Storage instead of MinIO

### ISSUE THREAD

**Issue by meeeo** [EtherealEngine/etherealengine#9027]
I followed the document trying to run the local storage, but didn't find the scripts: dev-reinit-fs and dev-fs .
So I run npm dev-reinit and npm dev anyway, but I got some "serve-local-files" errors .
What's wrong? thank you.
![Screen Shot 2023-10-10 at 4 31 54 PM](https://github.com/EtherealEngine/etherealengine/assets/5188710/13679d92-fa97-45e6-887c-6cbc74e0f8e2)
![Screen Shot 2023-10-10 at 4 34 10 PM](https://github.com/EtherealEngine/etherealengine/assets/5188710/7bf66660-1908-4578-8f9f-c6030c5a2f48)
![Screen Shot 2023-10-10 at 4 51 02 PM](https://github.com/EtherealEngine/etherealengine/assets/5188710/8997812a-a568-4cd9-abc8-b6b26d3d31b1)

**Comment by meeeo** [comment]
Thank you, I've followed your steps, but there's always that "serve-local-files" error messages.
![Screen Shot 2023-10-11 at 8 58 11 AM](https://github.com/EtherealEngine/etherealengine/assets/5188710/01f7d879-200e-4ed8-8ad8-ed1726758b8a)

**Comment by aditya-mitra** [comment]
@meeeo can you please recheck this now on the latest dev?

**Comment by meeeo** [comment]
I'm sorry just back to work these days.
It seems like still the same? Thank you.
But by modifying the script I got it working anyway.
![Screen Shot 2024-01-03 at 10 09 16 AM](https://github.com/EtherealEngine/etherealengine/assets/5188710/b26a6bbe-48be-457d-b6c8-db9de120a976)
![Screen Shot 2024-01-03 at 10 17 44 AM](https://github.com/EtherealEngine/etherealengine/assets/5188710/34a9b157-8b18-4553-9831-1e58e47f49cd)
