### ISSUE TITLE
[story] make behave-graph a patch instead of a separate fork 

### ISSUE THREAD

**Issue by SYBIOTE** [EtherealEngine/etherealengine#9069]
recent update to behave graph, made it clear that large changes to the behave-graph fork, will cause dev and exp to break, until the corresponding PRs for the engine to fix to same are not applied, to mitigate this, we propose that the repo be converted to a patch instead which stays in our ethereal engine codebase

**Comment by SYBIOTE** [comment]
@HexaField , please guide me on how to prepare a patch for this,

**Comment by HexaField** [comment]
> @HexaField , please guide me on how to prepare a patch for this,

- in your fork, do whatever changes and build necessary
- copy into node_modules in your destination repo
- run npx patch-package <packagename>
 
a patch file will appear in /patches, commit this
