### ISSUE TITLE
[Story] Specific service level scoping for each service

### ISSUE THREAD

**Issue by aditya-mitra** [EtherealEngine/etherealengine#9161]
Instead of `admin:admin` scope in our hooks, it would be better to have a specific service level scope `service:read` or `service:write`

This will properly limit the each service to their own scope only and not rely on the user being an admin.

`admin:admin` scope will tend to be the scope required for opening the admin panel/dashboard only

**Comment by HexaField** [comment]
Will this work when params are passed around internally? I'm not totally sure they should be this granular, but at the feature level.

For instance, the file browser API is an abstraction on top of static-resources.

We already have static resource scopes, it is redundant to have file browser scopes as well.

**Comment by aditya-mitra** [comment]
Yes, they will work when params are passed internally because `verifyScope` will only check scopes on user if the request is external. We will need to add a condition for `isInternal: true` explicitly.

I will use the static resource scopes instead of another file-browser scopes.
