### ISSUE TITLE
Studio must be obvious about when things are loading or has failed loading

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#9201]
Studio
- [ ] Inspector should  have loading icons for assets/components loading
- [ ] errors too

Client
- [ ] stand in loading icon or 3d gliph
- [ ] error system in 2d/3d too

Immersive scene loading screen looks nice

**Comment by aditya-mitra** [comment]
Error and loading working as intended in the components and in the studio.
