### ISSUE TITLE
Create Default Prefabs for Common Component Types

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9291]
To replace components panel, we should create basic prefabs that have the correct configurations for common ECS usage.

- Model Component with Shadow, Envmap, LoopAnimation components
- Model Component with Collider set to Mesh mode for Mesh Colliders
- Particle Systems with better default values
...etc

These will be dragged and dropped into scene from Assets Panel instead of from the Components Tab

**Comment by HexaField** [comment]
duplicate https://github.com/EtherealEngine/etherealengine/issues/10034
