### ISSUE TITLE
[Bug]: Studio not working properly on Firefox

### ISSUE THREAD

**Issue by CITIZENDOT** [EtherealEngine/etherealengine#9310]
### Version

0f27df2(1.5.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Android
- [ ] IOS

### Browser (if applicable)

Firefox

### What is supposed happened?

Studio should open & work as expected

### What happened?

Lots of repeated errors due to PositionalAudio in console
![image](https://github.com/EtherealEngine/etherealengine/assets/52322531/c622212a-6a63-48e4-a668-bef6cbf8839e)

### Steps to reproduce

```shell
Open this: https://localhost:3000/studio/default-project in firefox after setting up the user as admin.
```

**Comment by SYBIOTE** [comment]
i guess, audio context on firefox doesnt provide the key called positionX?
