### ISSUE TITLE
Batched Compression

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9402]
Add barebones batch capability to Model Transform
Currently, gltf files are compressed in the engine through the Model Transform menu:

![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/c370e143-ee7f-4d86-a46e-0d4a2390f3e4)

Only one compression job is performed at a time, and the user must manually specify each compression configuration.
As we move toward automatic LOD generation, we need to execute multiple compression jobs in batches.
90% of compression will use the default settings:
- Join all meshes
- Instance all duplicate geo
- run Meshoptimizer on all geo
- compress all images to ktx2
- resample all animation curves

The biggest difference between the different LOD levels is the texture resolution.

Add a "Batch Compress" option to the GLTFTransformProperties.tsx panel, which, when checked, makes the engine execute three compression jobs, with the only difference being the output file name and the texture resolution.

Each output file should be given a "LOD_x" suffix, with x being the LOD level. 

LOD_0: Texture resolution at 2048
LOD_1: Texture resolution at 1024
LOD_2: Texture resolution at 512

This functionality should be implemented entirely within ModelTransformProperties.tsx. You will need to:
1. Add a toggle labeled "Batch Transform" under the "Clientside Transform" toggle in the menu
2. Edit the onTransformModel callback to run the three compression jobs with different max texture resolution if the "Batch Transform" toggle is enabled

**Comment by Rezmason** [comment]
Branch: `9402-batched-compression-phase-1`
