### ISSUE TITLE
[Bug]: Refresh not working on `/admin/server` table

### ISSUE THREAD

**Issue by hanzlamateen** [EtherealEngine/etherealengine#9426]
### Version

0f27df2(1.5.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

It should refresh the pod statuses

### What happened?

The table data is not refreshed

### Steps to reproduce

```shell
On deployment, go to `/admin/server` and hit refresh button on top right of table. It should refresh the table.
```

**Comment by aditya-mitra** [comment]
Seems to be working
