### ISSUE TITLE
Automatic Variant Configuration

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9435]
We want to automate the process of adding device-targeted LODs to 3D assets. We already have a variant system that allows us to have one object load specific assets for different device types. This should be automated and made part of the GLTF Transform pipeline.
Currently, the process for setting up LODs for a 3D model is as follows:
0. Compress the model into multiple LODs using manual settings
1. Add a Variant Component to the model:
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/15ed96be-ead0-4f3a-8834-ae3c6c025994)
2. Change the variant heuristic to Device:
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/dfaf3eb0-02af-4d3e-9f48-229c0e163d0b)
3. Add multiple variant levels to the component:
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/88b6ea37-4508-4658-8b0d-436d925d4e12)
4. For each level, assign a device type and drag and drop a 3d model URL from the file browser into the src input:
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/e9104d1f-41fa-43cc-80f3-10b9da3542a9)
5. To save this into a .gltf file, the object must now be wrapped within an additional Model Component and exported as its own file:

We should, as part of the batched compression workflow starting with #9402, add an option to generate an additional .gltf or .glb file that has these variants automatically configured. Steps 1-5 should be done procedurally with the resulting LODs from the batched compression, and the result should be saved into the same folder with the suffix `-device-LODs`. 
- Use the ee-tutorial-bubbles implementation as a reference to see how ECS data can be created with code. 
- At the end, use the ExportRelativeGLTF function to export + upload the prefab to the server

**Comment by Rezmason** [comment]
```
createEntity (create your own func to do this for now)
  transform component
  entity tree component
  name component
  visible component
create LODs with compression panel type stuff (copy-paste into a local func for now)
then use setComponent:
  container object
    model component used for exporting
  child object
    variant component used for LODs
    model component used for variant
run exportRelativeGLTF on parent
change the source of the original model component
  see if that works
```

**Comment by Rezmason** [comment]
Branch: `9435-automatic-variant-configuration`
PR (WIP): https://github.com/EtherealEngine/etherealengine/pull/9499
