### ISSUE TITLE
[Bug] Multi avatar select delete doesn't refresh upon completetion

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#9452]
deleting multiple avatars worked but did not refresh the list when it completed

**Comment by aditya-mitra** [comment]
On checking, seems to be working as intended.

(in the video, I have added a 2 seconds sleep after the modal closes to ensure that the service.on method is working)
https://github.com/EtherealEngine/etherealengine/assets/55396651/2504dfc1-c4d2-4bf0-b57c-6c880bce9706
