### ISSUE TITLE
LOD List

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9507]
## LOD List in Compression Panel ##

![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/582df81e-f51c-4055-b179-14e272281b57)

Create a list UI element matching the above wireframe, where the LODs are ordered as clickable elements. The selected list element should be highlighted. There should be an "Add LOD Level" button at the bottom of the list which adds elements. Each element should have an 'x' button on their right side which removes the LOD level if clicked.

The compression settings in the center of the screen should represent the selected LOD level. Changing the settings should update the selected LOD level's parameters.

**Comment by speigg** [comment]
This looks great!

**Comment by speigg** [comment]
Question: does it make sense to think of these optimized assets as having a static linear progression (e.g. LOD 0, LOD 1 ... etc.) when there might be completely different optimization strategies for different circumstances (desktop vs mobile vs PC VR vs mobile XR) ? Wouldn't different circumstances warrant ordering these asset variants in different ways, depending on the resources being optimized (e.g., CPU, GPU, texture memory, etc) and the heuristics chosen?

**Comment by dinomut1** [comment]
> Question: does it make sense to think of these optimized assets as having a static linear progression (e.g. LOD 0, LOD 1 ... etc.) when there might be completely different optimization strategies for different circumstances (desktop vs mobile vs PC VR vs mobile XR) ? Wouldn't different circumstances warrant ordering these asset variants in different ways, depending on the resources being optimized (e.g., CPU, GPU, texture memory, etc) and the heuristics chosen ?
> 
> Perhaps a simple collection of optimization targets is more appropriate, and then the ordering of these can be handled at runtime, based on the optimization heuristics that are chosen (also at runtime) ?

Yes we should make this more multidimensional, as a next step. To start we just need a 1-D list of progressively more optimized assets, with certain elements on that list tagged as device targets. Distance LODs will be constructed by selecting a range of LOD levels starting at the tagged level.
This can be expanded upon to have different orderings, and multiple LOD lists using different optimization strategies depending on the target device.
